spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soumon
    username: postgres
    password: postgres
  mail:
    host: localhost
    port: 1025